# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god_name', models.CharField(max_length=30)),
                ('god_type', models.CharField(max_length=15)),
                ('god_class', models.CharField(max_length=30)),
                ('god_image', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=15)),
                ('role_gods', models.ManyToManyField(to='partyservice.Gods')),
            ],
        ),
    ]
